### ISSUE TITLE
Example input files

### ISSUE THREAD

**Issue by anjaseidel** [deepmedicine/BEHRT#3]
Hi, first of all, many thanks for providing the code of your nice work!
Would it be possible to upload small example files (data and vocab) in the correct format, so that everybody knows exactly how the input has to look like (without digging in the source code)?
Many thanks!

**Comment by anjaseidel** [comment]
Solved by myself

**Comment by yudeng2015** [comment]
Hi Could you share example file by any chance?

**Comment by jungel2star** [comment]
> Solved by myself

Dear Anja Seidel, could you provide more detail on how you solved this issue? Thank you ver much in advance.
